name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key
        ssh -o StrictHostKeyChecking=no -i ssh_key $SSH_USERNAME@$SSH_HOST << 'EOF'
          cd ~/SocialRating/
          git pull origin main  # Получаем последние изменения из репозитория
          docker-compose down # Останавливаем контейнеры
          docker image prune -f # Удаляем старые образы
          docker-compose up -d --build   # Перезапускаем контейнеры с новыми изменениями
        EOF
      # Cleanup step to remove the temporary ssh_key file
    - name: Cleanup
      run: |
        rm -f ssh_key
